### ISSUE TITLE
2.4.2 with instalation problem

### ISSUE THREAD

**Issue by CosmeFC** [Wargus/wargus#261]
Hi,

I am using W10 Pro.

Here some screenshots:

![image](https://user-images.githubusercontent.com/4854932/36185055-5b0148c4-111e-11e8-8f54-cbd5b8e94fbe.png)
![image](https://user-images.githubusercontent.com/4854932/36185097-88320dc4-111e-11e8-87f4-36f8f7ec4b77.png)

**Comment by MamiyaOtaru** [comment]
confirm this

**Comment by DinkyDyeAussie** [comment]
It will be a bug in the wartool code. I haven't looked at that code much but hopefully Tim will have a look at it when he gets time.

**Comment by MamiyaOtaru** [comment]
crash happens right after completing conversion of gameintro.ogv.  Presumably while working on orc-4.ogv 

As above, if I use an old wartool to extract everything, Stratagus crashes with the error in my image above.  I can get it to run by removing the videos folder.  No version of the videos from any previous wartool (or the current one, for the ones that finish before it crashes) allow the current Stratagus to load

**Comment by timfel** [comment]
Probably the same issue as https://github.com/Wargus/wargus/issues/263

**Comment by Erenussocrates** [comment]
I cannot find a file to extract the files at all. It says "use root folder" for Battle.net edition, but when I attempt to click "open", it opens the folder, the tool insists that I have to find a file called "rezdat.war" in order to extract stuff

**Comment by jacben** [comment]
I'm hitting the same issue @Erenussocrates . Did you ever figure it out?

**Comment by DinkyDyeAussie** [comment]
You have the battlenet.snp on the same drive as your game?

**Comment by timfel** [comment]
The crash should be fixed in trunk, the BNE extraction is tracked in #262

**Comment by dlasher** [comment]
> confirm this.
> 
> If I replace wartool.exe with an older copy, the extraction finishes. But doing so (or using older, previously successfully extracted data) then running wargus.exe tells me
> 
> "Stratagus failed to load game data etc.." Aleona's Tales launches fine, Wargus does not.
> 
> ![error](https://user-images.githubusercontent.com/2042826/37228668-99cd1e56-239e-11e8-962e-1ebd82fdd68f.png)
> 
> Using an older Stratagus.exe then allows Wargus to launch, but it's back to the old issue of mouse warping that was fixed with [Wargus/stratagus@47d3561](https://github.com/Wargus/stratagus/commit/47d35617ad71b41e5b94169b5c385a325cf337d8)

I can confirm this is still happening. First launch after install works, every launch after that fails to start.

**Comment by AviiNL** [comment]
> I'm choosing "battle.snp" to extract the files (as I have battle.net edition and the program does tell me to choose battle.snp if I have the BNE), but when I do it, it gives "Could not find Warcraft 2 data in folder. Make sure you have selected the DATA directory of the DOS version, or the root of the Battle.net CD"
> 
> Please someone help or fix this thing so that I can extract the files. This is exceedingly annoying.

I had this too, but selecting *any* file from the BNE disks root directory works, as far as i could tell, it only takes the directory of the file you selected as a base, and doesn't literally use the file itself that you selected.

**Comment by timfel** [comment]
I only realised now - @jacben tries to extract from an installation of Warcraft. The extractor only works from the BNE CD, not the installed thing, afaict

**Comment by jacben** [comment]
> I only realised now - @jacben tries to extract from an installation of Warcraft. The extractor only works from the BNE CD, not the installed thing, afaict

Thank you!

**Comment by timfel** [comment]
Btw, after some fixes the current nightly release now works extracting from BNE installation (or the GoG installation).
